apiVersion: v1
kind: Secret
metadata:
  name: prom-analytics-proxy
  labels:
    app: prom-analytics-proxy
stringData:
  config.yaml: |-
    # See https://github.com/nicolastakashi/prom-analytics-proxy/blob/main/internal/config/config.go
    # Server
    upstream:
      url: "http://prometheus:9090"
    memory_limit:
      enabled: true
    # Database
    database:
      provider: "postgresql"
      postgresql:
        addr: "postgresql"
        port: 5432
        database: "postgres"
        user: "postgres"
        password: "postgres"
        sslmode: "disable"
    insert:
      batch_size: 10
      buffer_size: 100
      flush_interval: "5s"
      grace_period: "5s"
      timeout: "1s"
