apiVersion: v1
kind: Secret
metadata:
  name: perses-metrics-usage
  labels:
    app: perses-metrics-usage
stringData:
  config.yaml: |-
    # See https://github.com/perses/metrics-usage/blob/main/docs/configuration.md

    metric_collector:
      enable: true
      # period: 12h # default 12h
      http_client:
        url: http://prometheus:9090

    labels_collectors:
      - enable: true
        # period: 12h
        prometheus_client:
          url: http://prometheus:9090
        metric_usage_client:
          url: http://prom-analytics-proxy:9091

    rules_collectors:
      - enable: true
        # period: 12h
        prometheus_client:
          url: http://prometheus:9090
        metric_usage_client:
          url: http://prom-analytics-proxy:9091

    grafana_collector:
      enable: true
      # period: 12h
      grafana_client:
        url: http://grafana:3000
        basic_auth:
          username: GRAFANA_USER
          password: SECRET_PASSWORD
      metric_usage_client:
        url: http://prom-analytics-proxy:9091
      ignore_datasource_types:
        - loki
        - postgres
