apiVersion: v1
kind: Service
metadata:
  name: perses-metrics-usage
  labels:
    app: perses-metrics-usage
spec:
  selector:
    app: perses-metrics-usage
  ports:
    - name: api
      port: 8080
      targetPort: api
