apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: postgresql
    headless: "false"
spec:
  selector:
    app: postgresql
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql

---
# INFO: required by StatefulSet
apiVersion: v1
kind: Service
metadata:
  name: postgresql-headless
  labels:
    app: postgresql
    headless: "true"
spec:
  clusterIP: None
  selector:
    app: postgresql
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
