apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  labels:
    app: postgresql
spec:
  serviceName: postgresql-headless
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      name: postgresql
      labels:
        app: postgresql
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
        - name: postgresql
          image: docker.io/postgres
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: postgresql
            - secretRef:
                name: postgresql
          ports:
            - name: postgresql
              containerPort: 5432
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - -e
                - |
                  pg_isready -U $POSTGRES_USER -d $POSTGRES_DB -h 127.0.0.1 -p 5432
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - -e
                - |
                  pg_isready -U $POSTGRES_USER -d $POSTGRES_DB -h 127.0.0.1 -p 5432
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            # Trick part 1.1 - This trick is to avoid to give containers write access to root filesystem
            - name: run
              mountPath: /var/run/postgresql
            # Trick part 1.2 - This trick is to avoid to give containers write access to root filesystem
            - name: tmp
              mountPath: /tmp
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
        labels:
          type: ssd
          expandable: "true"
      spec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
    # Trick part 2.1 - This trick is to avoid to give containers write access to root filesystem
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: run
        labels:
          type: ssd
          expandable: "true"
      spec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 250Mi
    # Trick part 2.2 - This trick is to avoid to give containers write access to root filesystem
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: tmp
        labels:
          type: ssd
          expandable: "true"
      spec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 250Mi
