// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "https://github.com/nicolastakashi/prom-analytics-proxy"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/configs": {
            "get": {
                "description": "Get sanitized server configuration (secrets redacted) as YAML.",
                "produces": [
                    "application/yaml"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Get configuration",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/jobs": {
            "get": {
                "description": "Get list of distinct job labels from stored series.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metrics"
                ],
                "summary": "List jobs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.JobsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/metricQueryPerformanceStatistics/{name}": {
            "get": {
                "description": "Get query performance statistics for a specific metric including query rate and performance metrics.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metrics"
                ],
                "summary": "Get metric query performance statistics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Metric name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Start time (RFC3339 or Unix)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End time (RFC3339 or Unix)",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/db.MetricQueryPerformanceStatistics"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/metricStatistics/{name}": {
            "get": {
                "description": "Get detailed statistics for a specific metric including series count, label count, and producers.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metrics"
                ],
                "summary": "Get metric statistics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Metric name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Start time (RFC3339 or Unix)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End time (RFC3339 or Unix)",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/db.MetricUsageStatics"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/metrics": {
            "post": {
                "description": "Receive metrics usage data from Perses client (alerts, recording rules, dashboards).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metrics"
                ],
                "summary": "Push metrics usage",
                "parameters": [
                    {
                        "description": "Metrics usage data from Perses",
                        "name": "metricsUsage",
                        "in": "body",
                        "required": true,
                        "schema": {}
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/metrics/unused": {
            "get": {
                "description": "Check if given metrics are unused based on alerts, recording rules, dashboards, and queries.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metrics"
                ],
                "summary": "Check unused metrics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Comma-separated metric names (max 100)",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Filter by job label",
                        "name": "job",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UnusedMetricsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/query": {
            "get": {
                "description": "Execute an instant PromQL query and forward to Prometheus. Results are logged for analytics.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "query"
                ],
                "summary": "Query instant",
                "parameters": [
                    {
                        "type": "string",
                        "description": "PromQL query expression",
                        "name": "query",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Evaluation timestamp (RFC3339 or Unix)",
                        "name": "time",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/query/average_duration": {
            "get": {
                "description": "Get average query duration in the given time range.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Average duration",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start time (RFC3339 or Unix)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End time (RFC3339 or Unix)",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Fingerprint filter",
                        "name": "fingerprint",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/db.AverageDurationResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/query/errors": {
            "get": {
                "description": "Get query error analysis in the given time range.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Error analysis",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start time (RFC3339 or Unix)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End time (RFC3339 or Unix)",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Fingerprint filter",
                        "name": "fingerprint",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.QueryErrorAnalysisResult"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/query/executions": {
            "get": {
                "description": "Get query execution history for a specific fingerprint with pagination.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Query executions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Query fingerprint",
                        "name": "fingerprint",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Start time (RFC3339 or Unix)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End time (RFC3339 or Unix)",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size (default 10)",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort field",
                        "name": "sortBy",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort order (asc or desc)",
                        "name": "sortOrder",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Query type filter (instant or range)",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.QueryExecutionsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/query/expressions": {
            "get": {
                "description": "Get list of unique query expressions in the given time range with pagination.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Query expressions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start time (RFC3339 or Unix)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End time (RFC3339 or Unix)",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size (default 10)",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort field (e.g., count, avg_duration)",
                        "name": "sortBy",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort order (asc or desc)",
                        "name": "sortOrder",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by expression pattern",
                        "name": "filter",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.QueryExpressionsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/query/latency": {
            "get": {
                "description": "Get query latency trends over time in the given time range.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Latency trends",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start time (RFC3339 or Unix)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End time (RFC3339 or Unix)",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Metric name filter",
                        "name": "metricName",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Fingerprint filter",
                        "name": "fingerprint",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.QueryLatencyTrendsResult"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/query/push": {
            "post": {
                "description": "Bulk push query execution data for analytics purposes.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Push query data",
                "parameters": [
                    {
                        "description": "Array of query execution records",
                        "name": "queries",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.Query"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/query/rate": {
            "get": {
                "description": "Get query rate (queries per second) in the given time range.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Query rate",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start time (RFC3339 or Unix)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End time (RFC3339 or Unix)",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Fingerprint filter",
                        "name": "fingerprint",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/db.QueryRateResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/query/status_distribution": {
            "get": {
                "description": "Get distribution of HTTP status codes returned by queries in the given time range.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Status distribution",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start time (RFC3339 or Unix)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End time (RFC3339 or Unix)",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Fingerprint filter",
                        "name": "fingerprint",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.QueryStatusDistributionResult"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/query/throughput": {
            "get": {
                "description": "Get query throughput analysis (samples processed per second) in the given time range.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Throughput analysis",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start time (RFC3339 or Unix)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End time (RFC3339 or Unix)",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.QueryThroughputAnalysisResult"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/query/time_range_distribution": {
            "get": {
                "description": "Get distribution of query time ranges in the given time range.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Time range distribution",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start time (RFC3339 or Unix)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End time (RFC3339 or Unix)",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Fingerprint filter",
                        "name": "fingerprint",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.QueryTimeRangeDistributionResult"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/query/types": {
            "get": {
                "description": "Get distribution of query types (instant vs range) in the given time range.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Query types",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start time (RFC3339 or Unix)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End time (RFC3339 or Unix)",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Fingerprint filter",
                        "name": "fingerprint",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/db.QueryTypesResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/query_range": {
            "get": {
                "description": "Execute a range PromQL query and forward to Prometheus. Results are logged for analytics.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "query"
                ],
                "summary": "Query range",
                "parameters": [
                    {
                        "type": "string",
                        "description": "PromQL query expression",
                        "name": "query",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Start timestamp (RFC3339 or Unix)",
                        "name": "start",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "End timestamp (RFC3339 or Unix)",
                        "name": "end",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Query resolution step (e.g., 15s)",
                        "name": "step",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/serieExpressions/{name}": {
            "get": {
                "description": "Get queries that referenced a specific series in the given time range.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metrics"
                ],
                "summary": "Serie expressions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Series name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size (default 1)",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort field",
                        "name": "sortBy",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort order (asc or desc)",
                        "name": "sortOrder",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by expression pattern",
                        "name": "filter",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start time (RFC3339 or Unix)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End time (RFC3339 or Unix)",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.SerieExpressionsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/serieUsage/{name}": {
            "get": {
                "description": "Get usage information for a specific metric (dashboards, alerts, recording rules).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metrics"
                ],
                "summary": "Get metric usage",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Metric name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Usage kind (dashboard, alert, recording)",
                        "name": "kind",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size (default 1)",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by name pattern",
                        "name": "filter",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort field",
                        "name": "sortBy",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort order (asc or desc)",
                        "name": "sortOrder",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start time (RFC3339 or Unix)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End time (RFC3339 or Unix)",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.MetricUsageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/seriesMetadata": {
            "get": {
                "description": "Get metadata for all series with pagination and filtering options.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metrics"
                ],
                "summary": "Series metadata",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size (default 10, max 100)",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort field (name, seriesCount, type, usage)",
                        "name": "sortBy",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort order (asc or desc)",
                        "name": "sortOrder",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by metric name pattern",
                        "name": "filter",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by metric type (gauge, counter, histogram, summary)",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by usage type (all, used, unused)",
                        "name": "usage",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by job label",
                        "name": "job",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filter for unused metrics only",
                        "name": "unused",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.SeriesMetadataResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "db.AverageDurationResult": {
            "type": "object",
            "properties": {
                "avg_duration": {
                    "type": "number"
                },
                "delta_percent": {
                    "type": "number"
                }
            }
        },
        "db.MetricProducersResult": {
            "type": "object",
            "properties": {
                "job": {
                    "type": "string"
                },
                "series": {
                    "type": "integer"
                }
            }
        },
        "db.MetricQueryPerformanceStatistics": {
            "type": "object",
            "properties": {
                "averageDuration": {
                    "type": "number"
                },
                "averageSamples": {
                    "type": "number"
                },
                "peakSamples": {
                    "type": "integer"
                },
                "queryRate": {
                    "$ref": "#/definitions/db.QueryRateResult"
                },
                "sampleRate": {
                    "type": "number"
                },
                "totalQueries": {
                    "type": "integer"
                }
            }
        },
        "db.MetricUsageStatics": {
            "type": "object",
            "properties": {
                "alertCount": {
                    "type": "integer"
                },
                "dashboardCount": {
                    "type": "integer"
                },
                "labelCount": {
                    "type": "integer"
                },
                "producers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/db.MetricProducersResult"
                    }
                },
                "recordCount": {
                    "type": "integer"
                },
                "serieCount": {
                    "type": "integer"
                },
                "totalAlerts": {
                    "type": "integer"
                },
                "totalDashboards": {
                    "type": "integer"
                },
                "totalRecords": {
                    "type": "integer"
                }
            }
        },
        "db.QueriesBySerieNameResult": {
            "type": "object",
            "properties": {
                "avgDuration": {
                    "type": "number"
                },
                "avgPeakySamples": {
                    "type": "number"
                },
                "httpHeaders": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "maxPeakSamples": {
                    "type": "integer"
                },
                "query": {
                    "type": "string"
                },
                "ts": {
                    "type": "string"
                }
            }
        },
        "db.Query": {
            "type": "object",
            "properties": {
                "body_size": {
                    "type": "integer"
                },
                "duration": {
                    "$ref": "#/definitions/time.Duration"
                },
                "end": {
                    "type": "string"
                },
                "http_headers": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "peak_samples": {
                    "type": "integer"
                },
                "query_param": {
                    "type": "string"
                },
                "start": {
                    "type": "string"
                },
                "status_code": {
                    "type": "integer"
                },
                "step": {
                    "type": "number"
                },
                "time_param": {
                    "type": "string"
                },
                "total_queryable_samples": {
                    "type": "integer"
                },
                "type": {
                    "$ref": "#/definitions/db.QueryType"
                }
            }
        },
        "db.QueryErrorAnalysisResult": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "db.QueryExecutionRow": {
            "type": "object",
            "properties": {
                "duration": {
                    "type": "integer"
                },
                "end": {
                    "type": "string"
                },
                "httpHeaders": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "samples": {
                    "type": "integer"
                },
                "start": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "steps": {
                    "type": "number"
                },
                "timestamp": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "db.QueryExpression": {
            "type": "object",
            "properties": {
                "avgDuration": {
                    "type": "number"
                },
                "errorRatePercent": {
                    "type": "number"
                },
                "executions": {
                    "type": "integer"
                },
                "fingerprint": {
                    "type": "string"
                },
                "peakSamples": {
                    "type": "integer"
                },
                "query": {
                    "type": "string"
                }
            }
        },
        "db.QueryLatencyTrendsResult": {
            "type": "object",
            "properties": {
                "p95": {
                    "type": "integer"
                },
                "time": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "db.QueryRateResult": {
            "type": "object",
            "properties": {
                "error_rate_percent": {
                    "type": "number"
                },
                "error_total": {
                    "type": "integer"
                },
                "success_rate_percent": {
                    "type": "number"
                },
                "success_total": {
                    "type": "integer"
                }
            }
        },
        "db.QueryStatusDistributionResult": {
            "type": "object",
            "properties": {
                "2xx": {
                    "type": "integer"
                },
                "4xx": {
                    "type": "integer"
                },
                "5xx": {
                    "type": "integer"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "db.QueryThroughputAnalysisResult": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "db.QueryTimeRangeDistributionResult": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "label": {
                    "type": "string"
                },
                "percent": {
                    "type": "number"
                }
            }
        },
        "db.QueryType": {
            "type": "string",
            "enum": [
                "range",
                "instant"
            ],
            "x-enum-varnames": [
                "QueryTypeRange",
                "QueryTypeInstant"
            ]
        },
        "db.QueryTypesResult": {
            "type": "object",
            "properties": {
                "instant_percent": {
                    "type": "number"
                },
                "range_percent": {
                    "type": "number"
                },
                "total_queries": {
                    "type": "integer"
                }
            }
        },
        "models.Data": {
            "type": "object",
            "properties": {
                "resultType": {
                    "type": "string"
                },
                "stats": {
                    "$ref": "#/definitions/models.Stats"
                }
            }
        },
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "error": {
                    "type": "string"
                },
                "traceId": {
                    "type": "string"
                }
            }
        },
        "models.JobsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "models.MetricMetadata": {
            "type": "object",
            "properties": {
                "alertCount": {
                    "type": "integer"
                },
                "dashboardCount": {
                    "type": "integer"
                },
                "help": {
                    "type": "string"
                },
                "lastQueriedAt": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "queryCount": {
                    "type": "integer"
                },
                "recordCount": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                },
                "unit": {
                    "type": "string"
                }
            }
        },
        "models.Response": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/models.Data"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "models.Samples": {
            "type": "object",
            "properties": {
                "peakSamples": {
                    "type": "integer"
                },
                "totalQueryableSamples": {
                    "type": "integer"
                }
            }
        },
        "models.Stats": {
            "type": "object",
            "properties": {
                "samples": {
                    "$ref": "#/definitions/models.Samples"
                },
                "timings": {
                    "$ref": "#/definitions/models.Timings"
                }
            }
        },
        "models.Timings": {
            "type": "object",
            "properties": {
                "evalTotalTime": {
                    "type": "number"
                },
                "execQueueTime": {
                    "type": "number"
                },
                "execTotalTime": {
                    "type": "number"
                },
                "innerEvalTime": {
                    "type": "number"
                },
                "queryPreparationTime": {
                    "type": "number"
                },
                "resultSortTime": {
                    "type": "number"
                }
            }
        },
        "models.UnusedMetric": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "summary": {
                    "$ref": "#/definitions/models.UnusedSummary"
                },
                "unused": {
                    "type": "boolean"
                }
            }
        },
        "models.UnusedMetricsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.UnusedMetric"
                    }
                }
            }
        },
        "models.UnusedSummary": {
            "type": "object",
            "properties": {
                "alert_count": {
                    "type": "integer"
                },
                "dashboard_count": {
                    "type": "integer"
                },
                "query_count": {
                    "type": "integer"
                },
                "record_count": {
                    "type": "integer"
                }
            }
        },
        "routes.MetricUsageItem": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "expression": {
                    "type": "string"
                },
                "group_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "kind": {
                    "type": "string"
                },
                "labels": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "serie": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "routes.MetricUsageResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/routes.MetricUsageItem"
                    }
                },
                "total": {
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                }
            }
        },
        "routes.QueryExecutionsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/db.QueryExecutionRow"
                    }
                },
                "total": {
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                }
            }
        },
        "routes.QueryExpressionsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/db.QueryExpression"
                    }
                },
                "total": {
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                }
            }
        },
        "routes.SerieExpressionsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/db.QueriesBySerieNameResult"
                    }
                },
                "total": {
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                }
            }
        },
        "routes.SeriesMetadataResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MetricMetadata"
                    }
                },
                "total": {
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                }
            }
        },
        "time.Duration": {
            "type": "integer",
            "format": "int64",
            "enum": [
                -9223372036854775808,
                9223372036854775807,
                1,
                1000,
                1000000,
                1000000000,
                60000000000,
                3600000000000
            ],
            "x-enum-varnames": [
                "minDuration",
                "maxDuration",
                "Nanosecond",
                "Microsecond",
                "Millisecond",
                "Second",
                "Minute",
                "Hour"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Prometheus Analytics Proxy API",
	Description:      "API for Prometheus Analytics Proxy - provides query analytics, metrics usage tracking, and proxy capabilities.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
